### ISSUE TITLE
How to set the maximum number of questions

### ISSUE THREAD

**Issue by JBX028** [ramsrigouthamg/Questgen.ai#10]
Hi,

The MCQ always generates a set of 2 questions/answers.
I have tried to play with the playload in order to pass max_question in addition to input_text but without success.

```
payload = {
    "input_text": "<input>",
    "max_question": 5
}
```

Thanks

**Comment by JBX028** [comment]
My fault.....I was using max_querstion and not max_question**s**
Closing this issue :)

**Comment by aravind-812** [comment]
@JBX028 
'max_questions' too is not working.
Did you find any solution regarding that?
