### ISSUE TITLE
Questgen supports GPU?

### ISSUE THREAD

**Issue by pqrz** [ramsrigouthamg/Questgen.ai#18]
Hi Team,

Questgen is very useful library for question generation.

We are able to use it well on CPU, but it consumes high runtime on large datasets.

Does Questgen also gives GPU support?

**Comment by ramsrigouthamg** [comment]
Hi @pqrz ,

The models are built over Huggingface itself so support GPU as well.
Although you might need slight changes to add device as GPU in the text decoding code.
