### ISSUE TITLE
Results from code dont match the results from online tool

### ISSUE THREAD

**Issue by mon28** [ramsrigouthamg/Questgen.ai#19]
@ramsrigouthamg @parthplc @Vaibhav-nn @okhiroyuki

Results observed on https://questgen.ai/ are far better than what we get locally after setting up the code for the same input text.
Could you help me understand the gap here?
Example text: "Python is a programming language. Created by Guido van Rossum and first released in 1991"
MCQ results on the URL: 
```
Q1) Who created Python?
A) Guido van Rossum
B) John G. Kemeny
C) Tim Peters
D) Bill Joy
E) None of the above


Q2) When was Python first released?
A) 1991
B) 1993
C) 1994


Q3) What programming language was created by Guido van Rossum?
A) Python
B) Perl
C) C++
D) Java
```

MCQ results from local code run:

```
Q1) What is Python?
A) C++
B) Scripting Language
C) Design Patterns

Q2) What is the programming language for Python?
A) C++
B) Java
C) Perl
```

As you can see, the quality of these questions is inferior, the second question doesn’t make sense!

**Comment by ramsrigouthamg** [comment]
Hi @mon28 !

The web version is built on advanced pipelines using OpenAI's GPT-3 so the results won't match with the library.

Thanks,
Ramsri

**Comment by mon28** [comment]
Thanks for the quick response @ramsrigouthamg 
Are there any steps I can follow to bring the library to the version hosted with the advanced pipelines?

**Comment by ramsrigouthamg** [comment]
Hi @mon28,

The advanced pipelines are developed as part of our paid offering online.
So they are not open-sourced for now.
