### ISSUE TITLE
"[E002] Can't find factory for 'tok2vec

### ISSUE THREAD

**Issue by sriprad** [ramsrigouthamg/Questgen.ai#22]
Hi Team,
I need help. When i run the below code it give me 
qg = main.QGen()
output = qg.predict_mcq(payload)
pprint (output)

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-7-1ba2426fbc5d> in <module>
----> 1 qg = main.QGen()
      2 output = qg.predict_mcq(payload)
      3 pprint (output)

~\AppData\Roaming\Python\Python38\site-packages\Questgen\main.py in __init__(self)
     46         self.device = device
     47         self.model = model
---> 48         self.nlp = spacy.load('en_core_web_sm')
     49 
     50         self.s2v = Sense2Vec().from_disk('s2v_old')

~\AppData\Roaming\Python\Python38\site-packages\spacy\__init__.py in load(name, **overrides)
     28     if depr_path not in (True, False, None):
     29         deprecation_warning(Warnings.W001.format(path=depr_path))
---> 30     return util.load_model(name, **overrides)
     31 
     32 

~\AppData\Roaming\Python\Python38\site-packages\spacy\util.py in load_model(name, **overrides)
    162             return load_model_from_link(name, **overrides)
    163         if is_package(name):  # installed as package
--> 164             return load_model_from_package(name, **overrides)
    165         if Path(name).exists():  # path to model data directory
    166             return load_model_from_path(Path(name), **overrides)

~\AppData\Roaming\Python\Python38\site-packages\spacy\util.py in load_model_from_package(name, **overrides)
    183     """Load a model from an installed package."""
    184     cls = importlib.import_module(name)
--> 185     return cls.load(**overrides)
    186 
    187 

~\AppData\Roaming\Python\Python38\site-packages\en_core_web_sm\__init__.py in load(**overrides)
      8 
      9 def load(**overrides):
---> 10     return load_model_from_init_py(__file__, **overrides)

~\AppData\Roaming\Python\Python38\site-packages\spacy\util.py in load_model_from_init_py(init_file, **overrides)
    226     if not model_path.exists():
    227         raise IOError(Errors.E052.format(path=path2str(data_path)))
--> 228     return load_model_from_path(data_path, meta, **overrides)
    229 
    230 

~\AppData\Roaming\Python\Python38\site-packages\spacy\util.py in load_model_from_path(model_path, meta, **overrides)
    207             config = meta.get("pipeline_args", {}).get(name, {})
    208             factory = factories.get(name, name)
--> 209             component = nlp.create_pipe(factory, config=config)
    210             nlp.add_pipe(component, name=name)
    211     return nlp.from_disk(model_path, exclude=disable)

~\AppData\Roaming\Python\Python38\site-packages\spacy\language.py in create_pipe(self, name, config)
    298                 raise KeyError(Errors.E108.format(name=name))
    299             else:
--> 300                 raise KeyError(Errors.E002.format(name=name))
    301         factory = self.factories[name]
    302         return factory(self, **config)

KeyError: "[E002] Can't find factory for 'tok2vec'. This usually happens when spaCy calls `nlp.create_pipe` with a component name that's not built in - for example, when constructing the pipeline from a model's meta.json. If you're using a custom component, you can write to `Language.factories['tok2vec']` or remove it from the model meta and add it via `nlp.add_pipe` instead."

**Comment by ramsrigouthamg** [comment]
This must be fixed with the newer Spacy version
