### ISSUE TITLE
No matching distribution for Spacy==2.2.4

### ISSUE THREAD

**Issue by KTG1** [ramsrigouthamg/Questgen.ai#32]
Hello,

When I try to download the Repository, it gives the error below.

ERROR: No matching distribution found for spacy==2.2.4

It happens after the "`!pip install git+https://github.com/ramsrigouthamg/Questgen.ai`" command.

Any idea?

**Comment by ramsrigouthamg** [comment]
Hi KTG1!
Fixed the current offering with Spacy upgraded version.
