### ISSUE TITLE
Contributing guidelines

### ISSUE THREAD

**Issue by harshil15999** [ramsrigouthamg/Questgen.ai#4]
Are there any contributing guidelines for this project?

**Comment by ramsrigouthamg** [comment]
@harshil15999 Nothing yet as the library is fairly new! Let us know what you want to add, and create a pull request. We can take a look.
Thanks !

**Comment by harshil15999** [comment]
Hey @ramsrigouthamg  I donot really have any ideas but really liked the demos of this library  on Linkedin. Perhaps you could open up some Issues as Features to be added.
