### ISSUE TITLE
Getting ValueError: Can't read file: s2v_old/cfg

### ISSUE THREAD

**Issue by vinidixit** [ramsrigouthamg/Questgen.ai#5]
Hi,

I am getting `ValueError: Can't read file: s2v_old/cfg` at line `main.QGen()`
I tried with other call `qe= main.BoolQGen()` which is running fine. I am using Python 3.7

**Comment by ramsrigouthamg** [comment]
Hi @vinidixit ! Thanks for opening an issue. We will look into it as soon as we get the time and respond back. Thanks!

**Comment by ramsrigouthamg** [comment]
@vinidixit Meanwhile can you give us more information? If the error happens in Google Colab or when you run locally? Can you give us more info on where you are running it? Thanks

**Comment by vinidixit** [comment]
I am running this for the first time in my local machine (MacBook) and
using Jupyter notebook.

**Comment by ramsrigouthamg** [comment]
@vinidixit Thanks! Meanwhile, you can experiment with our Google Colab notebook as we take a deeper look into local environment error.

**Comment by vinidixit** [comment]
Sure, thanks so much.

**Comment by parthplc** [comment]
I think it is not able to access the s2v_old.U might need to the given the exact path instead of relative path. In main.py change
```
self.s2v = Sense2Vec().from_disk('s2v_old')
## change to 
self.s2v = Sense2Vec().from_disk('path_ to_folder\s2v_old')
```
Hope this works!

**Comment by vinidixit** [comment]
It is working now. Thank you for your quick help. :)
