### ISSUE TITLE
Suggestion: Logging instead of print statements

### ISSUE THREAD

**Issue by dk-crazydiv** [ramsrigouthamg/Questgen.ai#6]
Awesome library! Beautifully written and easy-to-read code and well thought API/module design.  

I have one request that if a mode `debug:true` in payload or logging could be introduced, then it's much neater to use in a for-loop. `tqdm` progress-bar breaks with print statements like _Sense2vec_distractors successful for word_

**Comment by ramsrigouthamg** [comment]
Hi @dk-crazydiv ! Thanks a lot for taking a look at the library and providing suggestions. Will work on them.
