### ISSUE TITLE
Which datasets are used?

### ISSUE THREAD

**Issue by thomas-chauvet** [ramsrigouthamg/Questgen.ai#7]
Hello,

This project is really interesting!

Could you share which datasets are used for training? I didn't find it in the code.

Thanks in advance!

**Comment by ramsrigouthamg** [comment]
Hi @thomas-chauvet ! Thanks for checking.
You can find few pointers here - 
https://towardsdatascience.com/generating-boolean-yes-no-questions-from-any-content-using-t5-text-to-text-transformer-model-69f2744aff44
https://towardsdatascience.com/paraphrase-any-question-with-t5-text-to-text-transfer-transformer-pretrained-model-and-cbb9e35f1555

Mainly Quora Question pairs, BoolQ, Squad are the datasets used

**Comment by thomas-chauvet** [comment]
Thank you for your answer!
