### ISSUE TITLE
maximum sequence length

### ISSUE THREAD

**Issue by zamirsiddiqui** [ramsrigouthamg/Questgen.ai#8]
I am getting following error
**"Token indices sequence length is longer than the specified maximum sequence length for this model (988 > 512). Running this sequence through the model will result in indexing errors"**

My most of documents about 1000 length. Please have a look and guide me for the solution.

**Comment by Vaibhav-nn** [comment]
Hey @zamirsiddiqui , our current model has maximum input token length of 512 and thus the documents greater than that might create problems. For the docs ranging in the order of 1000, I would suggest to go with Longformer (Huggingface).

In future, we would try to rectify this problem of restricted token length.
