### ISSUE TITLE
main.QGen not working !

### ISSUE THREAD

**Issue by VinayChaudhari1996** [ramsrigouthamg/Questgen.ai#9]
![image](https://user-images.githubusercontent.com/42869040/101242967-fd1ec500-3722-11eb-9e3c-00be6683530e.png)

**Comment by Vaibhav-nn** [comment]
Hey @VinayChaudhari1996 , I reckon you haven't installed sense2vec or the tar file that contains the word vectors. Also, you can try it on a Jupyter/Kaggle notebook in a new environment just to make sure that sense2vec is causing the issue.

**Comment by Vaibhav-nn** [comment]
You can refer to this blog also: https://towardsdatascience.com/questgen-an-open-source-nlp-library-for-question-generation-algorithms-1e18067fcdc6
